# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0
exclude: "^LICENSES"

ci:
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ["--maxkb=2000"]

# Run ruff to lint and format
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.3
  hooks:
    # Run the linter.
  - id: ruff
    args: [--fix]
    # Run the formatter.
  - id: ruff-format

  # Find common spelling mistakes in comments and docstrings
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ['--ignore-regex="(\b[A-Z]+\b)"', '--ignore-words-list=fom,appartment,bage,ore,setis,tabacco,berfore,vor,pris,bund'] # Ignore capital case words, e.g. country codes
    types_or: [python, rst, markdown]
    files: ^(scripts|doc)/

  # Check for FSFE REUSE compliance (licensing)
- repo: https://github.com/fsfe/reuse-tool
  rev: v6.0.0
  hooks:
  - id: reuse-lint-file
